### PR TITLE
Merge updates sentosa to demo branch

### PR DESCRIPTION
**Pull request by zwzac**
Update a spare simulation branch with the merge

### CODE REVIEW

**Comment by zwzac** [comment]
Weird github behaviour after resolving conflicts: merge goes into sentosa branch instead of demo branch

**Comment by acekillersg** [comment]
> Weird github behaviour after resolving conflicts: merge goes into sentosa branch instead of demo branch

@zwzac what happened here? I didn't see the merge goes into sentosa branch.

**Comment by zwzac** [comment]
@acekillersg I cancelled the merge because after resolving the conflicts on github website the merge show that it will update the sentosa branch instead of the demo branch. There was no change to the sentosa branch.

**Comment by zwzac** [comment]
I have done the merge to update the demo branch for the NAII demo. After some testing if the version is a stable demo version i will update the sentosa-simulation branch as well.

**Pull request closed without merging**
